import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/hooks/useAuth';

// Components
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const roboto = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PedagoGen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body className="h-screen">
        <div className="flex flex-col h-screen overflow-hidden">
          {/* The Navbar will grow or shrink based on its content */}
          <AuthProvider>
            <Navbar />

            {/* The main area fills the remaining space and handles scrolling */}
            <main className="flex-1 overflow-y-auto">
              {children}
            </main>
            <ToastContainer />
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
